### ISSUE TITLE
Fix name

### ISSUE THREAD

**Issue by DavidSchinazi** [DavidSchinazi/draft-schinazi-httpbis-transport-auth#3]
The title "HTTP Transport Authentication" no longer matches what this does, we should fix it

**Comment by m4mb01t4l14n0** [comment]
Candidates:
- Silent HTTP Client Authentication
- Quiet HTTP Client Authentication
- 0RTT HTTP Client Authentication

Is the term "client" actually necessary?

**Comment by DavidSchinazi** [comment]
That's a good point, I don't think we need "client" in the name. A few more ideas:

- HTTP Hidden Authentication
- HTTP Masked Authentication
